name: pixplay
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter

  shared_preferences:
  cupertino_icons: ^1.0.8
  flutter_svg:
  firebase_core: ^3.6.0
  app_tracking_transparency: ^2.0.6
  flutter_asa_attribution: ^1.0.0
  connectivity_plus:
  firebase_database: ^11.1.4
  audioplayers: ^6.1.0
  flutter_inappwebview: ^6.1.0
  url_launcher: ^6.1.10
  onesignal_flutter: ^5.1.2
  appsflyer_sdk: ^6.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/levels/
    - assets/bg/
    - assets/cards/
    - assets/buttons/
    - assets/buttons/pairs/
    - assets/audio/music.mp3